### ISSUE TITLE
Running with CKAN 2.3 

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckanext-qa#11]
Hi,

Is this extension working only with CKAN 1.5 or will it run with higher as well. If so what is the highest version it will run with?

Running with CKAN 2.3 throws errors:

Runnning `$ paster qa update` throws:
**requests.exceptions.MissingSchema: Invalid URL u'api/action/current_package_list_with_resources': No schema supplied**
```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/home/krzysiek/WebServer/ckan/lib/default/src/ckanext-qa/ckanext/qa/commands.py", line 73, in command
    for package in self._package_list():
  File "/home/krzysiek/WebServer/ckan/lib/default/src/ckanext-qa/ckanext/qa/commands.py", line 136, in _package_list
    response = self.make_post(url, {'page': page, 'limit': limit})
  File "/home/krzysiek/WebServer/ckan/lib/default/src/ckanext-qa/ckanext/qa/commands.py", line 109, in make_post
    return requests.post(url, data=json.dumps(data), headers=headers)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/api.py", line 87, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/sessions.py", line 276, in request
    prep = req.prepare()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/models.py", line 221, in prepare
    p.prepare_url(self.url, self.params)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/models.py", line 287, in prepare_url
    raise MissingSchema("Invalid URL %r: No schema supplied" % url)
requests.exceptions.MissingSchema: Invalid URL u'api/action/current_package_list_with_resources': No schema supplied
```

Running `$ paster qa update some_package` throws:
**requests.exceptions.MissingSchema: Invalid URL u'api/action/package_show': No schema supplied**
```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/home/krzysiek/WebServer/ckan/lib/default/src/ckanext-qa/ckanext/qa/commands.py", line 73, in command
    for package in self._package_list():
  File "/home/krzysiek/WebServer/ckan/lib/default/src/ckanext-qa/ckanext/qa/commands.py", line 126, in _package_list
    response = self.make_post(url, data)
  File "/home/krzysiek/WebServer/ckan/lib/default/src/ckanext-qa/ckanext/qa/commands.py", line 109, in make_post
    return requests.post(url, data=json.dumps(data), headers=headers)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/api.py", line 87, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/sessions.py", line 276, in request
    prep = req.prepare()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/models.py", line 221, in prepare
    p.prepare_url(self.url, self.params)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/requests/models.py", line 287, in prepare_url
    raise MissingSchema("Invalid URL %r: No schema supplied" % url)
requests.exceptions.MissingSchema: Invalid URL u'api/action/package_show': No schema supplied
```

**Comment by KrzysztofMadejski** [comment]
The problem was with `ckan.site_url`. It needs scheme prefix. Now it runs nicely.
```ini
# Remember to prefix with scheme (http:// or https://)
ckan.site_url = http://localhost:5000
```
