### ISSUE TITLE
Errors and no qa results

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckanext-qa#13]
I've encountered following error from celerytask while performing QA. Do you have any idea what could cause it?

```
[2015-02-03 16:11:33,059: ERROR/MainProcess] Task qa.update[507f23c7-9eca-4f03-bd83-10616cad1ee7] raised exception: KeyError('package',)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/home/krzysiek/WebServer/ckan/lib/default/src/ckanext-qa/ckanext/qa/tasks.py", line 122, in update
    data['package'], data['position'],
KeyError: 'package'
```

**Comment by KrzysztofMadejski** [comment]
I've corrected that in some commit as far as I remember.  See history for details.
