### ISSUE TITLE
paster qa update fails on ckanapi error

### ISSUE THREAD

**Issue by florianm** [ckan/ckanext-qa#25]
```
(datacats)me@IP:/mnt/projects/datacats/private/ckanext-qa⟫ datacats paster qa update
2015-11-17 04:10:07,343 ERROR [ckanext.qa] Failed to get package list with resources from url 'http://internal-data.dpaw.wa.gov.au/api/action/current_package_list_with_resources': Forbidden
Traceback (most recent call last):
  File "/usr/lib/ckan/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/project/ckanext-qa/ckanext/qa/commands.py", line 73, in command
    for package in self._package_list():
  File "/project/ckanext-qa/ckanext/qa/commands.py", line 141, in _package_list
    raise CkanApiError(err)
ckanext.qa.commands.CkanApiError: Failed to get package list with resources from url 'http://internal-data.dpaw.wa.gov.au/api/action/current_package_list_with_resources': Forbidden
```
* Datacats CKAN, latest master (2.5.0a)
* datacats wrapper fills in --plugin=qa and path to config
* celery is running (`datacats paster -d celeryd`)
* latest ckanext-qa master
* I can access http://internal-data.dpaw.wa.gov.au/api/action/current_package_list_with_resources without authentication (private browser window), so the CKAN API endpoint is fine.

**Comment by davidread** [comment]
BTW https://github.com/ckan/ckanext-qa/pull/24 is about to be merged which may affect this.

**Comment by KrzysztofMadejski** [comment]
@florianm this should be resolved by now. could you check? Can you write a test for it?

**Comment by florianm** [comment]
@KrzysztofMadejski thanks, can try but will take a few days!
