### ISSUE TITLE
Import Error: from kombu import virtual

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckanext-qa#45]
```
(ckan)ckan@km:~/src/ckanext-qa$ paster --plugin=ckanext-qa qa update --config=/etc/ckan/prod.ini 
Traceback (most recent call last):
[...]
  File "/home/ckan/.virtualenvs/ckan/local/lib/python2.7/site-packages/kombu/transport/__init__.py", line 76, in _get_transport_cls
    __import__(transport_module_name)
  File "/home/ckan/.virtualenvs/ckan/local/lib/python2.7/site-packages/kombu/transport/sqlalchemy/__init__.py", line 10, in <module>
    from kombu import virtual
ImportError: cannot import name virtual
(ckan)ckan@km:~/src/ckanext-qa$ pip freeze | grep kombu
kombu==2.1.8
kombu-sqlalchemy==1.1.0
```

Can be related to #22 and other kombu-related issues

**Comment by KrzysztofMadejski** [comment]
This was resolved in #50
