### ISSUE TITLE
'thread._local' object has no attribute 'host'

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckanext-qa#46]
When running `paster qa update dataset_id` I'm getting the following error. I have no idea how to tackle it.

My config file:
```
[server:main]
use = egg:Paste#http
host = 0.0.0.0
port = 5000
```
so the host is defined.

Stacktrace:
```
[2017-03-14 16:41:04,269: ERROR/MainProcess] Task qa.update_package[zbior-103f] raised exception: AttributeError("'thread._local' object has no attribute 'host'",)
Traceback (most recent call last):
  File "/home/ckan/.virtualenvs/ckan/local/lib/python2.7/site-packages/celery/execute/trace.py", line 47, in trace
    return cls(states.SUCCESS, retval=fun(*args, **kwargs))
  File "/home/ckan/.virtualenvs/ckan/local/lib/python2.7/site-packages/celery/app/task/__init__.py", line 247, in __call__
    return self.run(*args, **kwargs)
  File "/home/ckan/.virtualenvs/ckan/local/lib/python2.7/site-packages/celery/app/__init__.py", line 175, in run
    return fun(*args, **kwargs)
  File "/home/ckan/.virtualenvs/ckan/src/ckanext-qa/ckanext/qa/tasks.py", line 68, in update_package
    update_package_(package_id, log)
  File "/home/ckan/.virtualenvs/ckan/src/ckanext-qa/ckanext/qa/tasks.py", line 93, in update_package_
    _update_search_index(package.id, log)
  File "/home/ckan/.virtualenvs/ckan/src/ckanext-qa/ckanext/qa/tasks.py", line 419, in _update_search_index
    package = toolkit.get_action('package_show')(context_, {'id': package_id})
  File "/home/ckan/.virtualenvs/ckan/src/ckan/ckan/logic/__init__.py", line 424, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/ckan/.virtualenvs/ckan/src/ckan/ckan/logic/action/get.py", line 931, in package_show
    package_dict = model_dictize.package_dictize(pkg, context)
  File "/home/ckan/.virtualenvs/ckan/src/ckan/ckan/lib/dictization/model_dictize.py", line 216, in package_dictize
    result_dict["resources"] = resource_list_dictize(result, context)
  File "/home/ckan/.virtualenvs/ckan/src/ckan/ckan/lib/dictization/model_dictize.py", line 66, in resource_list_dictize
    resource_dict = resource_dictize(res, context)
  File "/home/ckan/.virtualenvs/ckan/src/ckan/ckan/lib/dictization/model_dictize.py", line 126, in resource_dictize
    qualified=True)
  File "/home/ckan/.virtualenvs/ckan/src/ckan/ckan/lib/helpers.py", line 142, in url_for
    my_url = _routes_default_url_for(*args, **kw)
  File "/home/ckan/.virtualenvs/ckan/local/lib/python2.7/site-packages/routes/util.py", line 257, in url_for
    host = config.host
  File "/home/ckan/.virtualenvs/ckan/local/lib/python2.7/site-packages/routes/__init__.py", line 14, in __getattr__
    return getattr(self.__shared_state, name)
AttributeError: 'thread._local' object has no attribute 'host'

```

**Comment by KrzysztofMadejski** [comment]
Ref https://github.com/ckan/ckan/issues/3145
