### ISSUE TITLE
from six import viewkeys: cannot import name viewkeys

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckanext-qa#55]
Thrown while calling celery: `paster --plugin=ckanext-archiver celeryd2 run all`
Runs on my local machine (six==1.10.0), but not on the server that was setuped earlier (six==1.7.3)
Call stack: QA -> messytables -> html5lib.

**Quickfix**: `pip install six==1.10.0`

Diagnosis with `pipdeptree -p six -r`:
1) Local
```
six==1.10.0
  - bleach==1.4.2 [requires: six]
  - html5lib==0.9999999 [requires: six] (seven 9s)
    - bleach==1.4.2 [requires: html5lib>=0.999]
    - messytables==0.15.2 [requires: html5lib]
      - ckanext-qa==2.0 [requires: messytables~=0.15.2]
  - PasteScript==2.0.2 [requires: six]
    - Pylons==0.9.7 [requires: PasteScript>=1.7.3]
  - pip-tools==1.1.2 [requires: six]
  - sqlalchemy-migrate==0.9.1 [requires: six>=1.4.1]
```
2) Server 
```
six==1.7.3
  - html5lib==0.999999999 [requires: six]  (nine 9s)
    - messytables==0.15.2 [requires: html5lib]
      - ckanext-qa==2.0 [requires: messytables>=0.15]
  - sqlalchemy-migrate==0.9.1 [requires: six>=1.4.1]
```

Conclusions:
1) offtop: WTF is 0.9999999 version of html5lib? I guess if versions would be txt based it wuld be finall-final-final
2) some googling points to https://github.com/html5lib/html5lib-python/issues/298 that has been merged in Oct 2016, but no release has been made since then, so it's good to pinpoint six version here
3) [fix belongs to messytables](https://github.com/okfn/messytables/issues/168) (if not html5lib), but till it's fixed there it's good to bump it here as well. 

Full stack trace:
```
Traceback (most recent call last):
[...]
  File "/home/ckan/.virtualenvs/ckan/src/ckanext-qa/ckanext/qa/tasks.py", line 17, in <module>
    from ckanext.qa.sniff_format import sniff_file_format
  File "/home/ckan/.virtualenvs/ckan/src/ckanext-qa/ckanext/qa/sniff_format.py", line 10, in <module>
    import messytables
  File "/home/ckan/.virtualenvs/ckan/local/lib/python2.7/site-packages/messytables/__init__.py", line 21, in <module>
    from messytables.html import HTMLTableSet, HTMLRowSet
  File "/home/ckan/.virtualenvs/ckan/local/lib/python2.7/site-packages/messytables/html.py", line 4, in <module>
    import html5lib
  File "/home/ckan/.virtualenvs/ckan/local/lib/python2.7/site-packages/html5lib/__init__.py", line 16, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "/home/ckan/.virtualenvs/ckan/local/lib/python2.7/site-packages/html5lib/html5parser.py", line 2, in <module>
    from six import with_metaclass, viewkeys, PY3
ImportError: cannot import name viewkeys
```

**Comment by th3w01f** [comment]
thanks, fixed for me
