### ISSUE TITLE
qa error

### ISSUE THREAD

**Issue by psonis** [ckan/ckanext-qa#62]
I get this error in the terminal when running it...
I use ckan 2.6.6.
The archiver/report works but I get no start in the openess section

`[2018-07-19 13:08:34,246: ERROR/MainProcess] Task qa.update_package[another-test-ef74] raised unexpected: AttributeError("'update_package' object has no attribute 'get_logger'",)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/hit/ckan/lib/default/src/ckanext-qa/ckanext/qa/tasks.py", line 83, in update_package
    log = update_package.get_logger()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/local.py", line 143, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'update_package' object has no attribute 'get_logger'
[2018-07-19 13:08:34,251: ERROR/MainProcess] Task qa.update_package[test-82aa] raised unexpected: AttributeError("'update_package' object has no attribute 'get_logger'",)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/hit/ckan/lib/default/src/ckanext-qa/ckanext/qa/tasks.py", line 83, in update_package
    log = update_package.get_logger()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/local.py", line 143, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'update_package' object has no attribute 'get_logger'
`

**Comment by Baehn** [comment]
same problem here

**Comment by psonis** [comment]
Did you manage to solve it?

**Comment by Baehn** [comment]
The plugin is for some reason not able to fetch a logger instance. I solved the problem by manually creating my own logger instance in the qa script. 
So only a quick and dirty fix.

**Comment by psonis** [comment]
Still its a fix! Could you help me create one as well?

**Comment by Baehn** [comment]
in "ckanext-qa/ckanext/qa/tasks.py" comment out all lines with "log = ..." then add the following lines after the import statements at the top of the file:

import logging  
log = logging.getLogger(__name__) 

that should do the trick!

**Comment by psonis** [comment]
thanks for the fix... the error is gone but still no stars, the Openess section is empty and now I get the error below.

Also, If I remove **qa** from the plugins sections in my .ini file I get a similar message for the archiver plugin. Please see [https://github.com/ckan/ckanext-archiver/issues/59](url)


`2018-08-08 11:37:48,828 ERROR [ckanext.qa.tasks] Exception occurred during QA update_package: AttributeError: 'NoneType' object has no attribute 'ugettext'
[2018-08-08 11:37:48,832: ERROR/MainProcess] Task qa.update_package[test-37f2] raised unexpected: AttributeError("'NoneType' object has no attribute 'ugettext'",)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/hit/ckan/lib/default/src/ckanext-qa/ckanext/qa/tasks.py", line 89, in update_package
    update_package_(package_id, log)
  File "/home/hit/ckan/lib/default/src/ckanext-qa/ckanext/qa/tasks.py", line 106, in update_package_
    qa_result = resource_score(resource, log)
  File "/home/hit/ckan/lib/default/src/ckanext-qa/ckanext/qa/tasks.py", line 230, in resource_score
    score_reason = _("Unknown error: %s") % str(e)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/i18n/translation.py", line 106, in ugettext
    return pylons.translator.ugettext(value)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/registry.py", line 137, in __getattr__
    return getattr(self._current_obj(), attr)
AttributeError: 'NoneType' object has no attribute 'ugettext'
`

Any ideas?

**Comment by Baehn** [comment]
This is a problem with ckans translation function "_" , in your stacktrace

"score_reason = _("Unknown error: %s") % str(e)"

I dont know yet why this is not working. I have the same problem with my ckan installation. Maybe a configuration problem. A very ugly hack is to simply mock the "_" function by inserting

def _(s): return s

on top of the qa and archiver scripts which disables translations.

**Comment by psonis** [comment]
I wasn't using any other language anyways... so it will do just fine!
Could you please be more specific as to which files should I add the def _(s): return s line?
Thanks in advance.

**Comment by Baehn** [comment]
try ckanext-qa/ckanext/qa/tasks.py

**Comment by psonis** [comment]
ok here's an update..
I added the line and no I get the stars on the left! 
...but the process in the terminal still hangs. See the error below.

Perhaps it should be added in another file or in report or in archiver? Really dont have a clue. Thanks. 

`[2018-08-08 12:53:54,574: ERROR/MainProcess] Task qa.update_package[test-754f] raised unexpected: AttributeError("'NoneType' object has no attribute 'ugettext'",)
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/hit/ckan/lib/default/src/ckanext-qa/ckanext/qa/tasks.py", line 90, in update_package
    update_package_(package_id, log)
  File "/home/hit/ckan/lib/default/src/ckanext-qa/ckanext/qa/tasks.py", line 115, in update_package_
    _update_search_index(package.id, log)
  File "/home/hit/ckan/lib/default/src/ckanext-qa/ckanext/qa/tasks.py", line 440, in _update_search_index
    package = toolkit.get_action('package_show')(context_, {'id': package_id})
  File "/home/hit/ckan/lib/default/src/ckan/ckan/logic/__init__.py", line 431, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/hit/ckan/lib/default/src/ckan/ckan/logic/action/get.py", line 976, in package_show
    package_dict = model_dictize.package_dictize(pkg, context)
  File "/home/hit/ckan/lib/default/src/ckan/ckan/lib/dictization/model_dictize.py", line 301, in package_dictize
    result_dict['license_title'] = pkg.license.title.split('::')[-1]
  File "/home/hit/ckan/lib/default/src/ckan/ckan/model/license.py", line 50, in __getattr__
    return self._data[name]
  File "/home/hit/ckan/lib/default/src/ckan/ckan/model/license.py", line 201, in __getitem__
    value = getattr(self, key)
  File "/home/hit/ckan/lib/default/src/ckan/ckan/model/license.py", line 242, in title
    return _("Open Data Commons Open Database License (ODbL)")
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/i18n/translation.py", line 106, in ugettext
    return pylons.translator.ugettext(value)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/registry.py", line 137, in __getattr__
    return getattr(self._current_obj(), attr)
AttributeError: 'NoneType' object has no attribute 'ugettext'
`

**Comment by Baehn** [comment]
yes, you can see it in the stacktrace:

"/home/hit/ckan/lib/default/src/ckan/ckan/model/license.py", line 242, in title return _("Open Data Commons Open Database License (ODbL)")

here is the "_" function used again, but this time not in the qa or archiver plugin. If you want to go down this road you can try to insert the mock there too until all errors go away.

**Comment by psonis** [comment]
thanks for all this! let me know if you think of anything else.

**Comment by Baehn** [comment]
still a hack but better: in both tasks.py (in qa and archiver):

search for
    class FakePylons:
            translator = None

and replace it with
    class FakeTranslator:
        def ugettext(s, a): return a

    class FakePylons:
            translator = FakeTranslator()

with this all errors go away for me, but you should still watch the logs of the archiver run as it showed some configuration problems of my installation

**Comment by psonis** [comment]
yep, now it works! hopefully there will be an official fix, but this will do just fine!
thanks again for all your effort!
